dotnet build ReportsMicroservice/ReportsMicroservice.csproj
dotnet build CardsMicroservice/CardsMicroservice.csproj
dotnet build LoansMicroservice/LoansMicroservice.csproj
dotnet build PaymentsMicroservice/PaymentsMicroservice.csproj
dotnet build AccountsMicroservice/AccountsMicroservice.csproj
dotnet build TransactionsMicroservice/TransactionsMicroservice.csproj
dotnet build UsersMicroservice/UsersMicroservice.csproj