start powershell -noexit -command "cd APIGateway; dotnet run"
start powershell -noexit -command "cd AccountsMicroservice; dotnet run"
start powershell -noexit -command "cd TransactionsMicroservice; dotnet run"
start powershell -noexit -command "cd UsersMicroservice; dotnet run"
start powershell -noexit -command "cd PaymentsMicroservice; dotnet run"
start powershell -noexit -command "cd LoansMicroservice; dotnet run"
start powershell -noexit -command "cd CardsMicroservice; dotnet run"